config/routes.rb
Lazycats::Application.routes.draw do

  root to: 'lazies#home'

  match '/',        to: 'lazies#home',      via: 'get'
  match '/signup',  to: 'users#new',        via: 'get'
  match '/signin',  to: 'sessions#new',     via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  match '/help',    to: 'lazies#help',      via: 'get'
  match '/about',   to: 'lazies#about',     via: 'get'

  

end

app/models/user.rb
class User < ActiveRecord::Base
	before_save { self.email = email.downcase }
 	validates :name, presence: true, length: { maximum: 50 }
 	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
 	validates :email, presence: true,
 						format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/lazies_controller.rb
class LaziesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
			user = User.find_by(email: params[:session][:email].downcase)
  			if user && user.authenticate(params[:session][:password])
    		# Sign the user in and redirect to the user's show page.
    			sign_in user
      			redirect_to user
  			else
    		# Create an error message and re-render the signin form.
    			flash[:error] = 'Invalid email/password combination' # Not quite right!
      			render 'new'
  			end
	end

	def destroy
		sign_out
    redirect_to root_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def show
  	@user = User.find(params[:id])
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

	# Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Lazy cats"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end

end

app/helpers/lazies_helper.rb
module LaziesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def sign_in(user)
    	remember_token = User.new_remember_token
    	cookies.permanent[:remember_token] = remember_token
    	user.update_attribute(:remember_token, User.encrypt(remember_token))
    	self.current_user = user
	end

	def signed_in?
		!current_user.nil?
	end

	def current_user=(user)
    	@current_user = user
  end

  def current_user
  	remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end
end

app/helpers/users_helper.rb
module UsersHelper

	  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
  
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="">Lazy cats</a>
    by Lazy Cat !
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Lazy cats", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <% if signed_in? %>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", '#' %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign up", signup_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
      <div class="container">
        <% flash.each do |key, value| %>
          <div class="alert alert-<%= key %>"><%= value %></div>
        <% end %>
        <%= yield %>
      </div>
  </body>
  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
</html>

app/views/lazies/about.html.erb
<% provide(:title, 'About') %>

    <h1>About Lazy cats</h1>
    <p style="text-indent: 2em">The question of feline fatigue is a controversial one.</p> 
	<p style="text-indent: 2em">Some may give cats the label of laziness because of their unique sleeping habits. Others may say cats are lazy because they won't fetch a ball like Fido does. </p> 
	<p style="text-indent: 2em">To understand cats, one must take a look at their evolutionary history.</p>

app/views/lazies/help.html.erb
<% provide(:title, 'Help') %>

	<h1>Help</h1>
	<p>Find me in app/views/lazies/help.html.erb</p>

app/views/lazies/home.html.erb
 	<%= image_tag("bg000.jpg", alt: "Lazy cats") %> 
 	<% if signed_in? %>
 		<p>花相似，花相似，相似送花花相似，相似花不开；</p>
		<p>久相思，久相思，相思还久久想思，相思久不归。</p>
 	<% else %>  		 	
 		<%= render 'sessions/new' %>
 	<% end %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign Up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
    	<%= render 'shared/error_messages' %>

     	<%= f.label :name %>
      <%= f.text_field :name %>

     	<%= f.label :email %>
     	<%= f.text_field :email %>

     	<%= f.label :password %>
      	<%= f.password_field :password %>

     	<%= f.label :password_confirmation, "Confirmation" %>
     	<%= f.password_field :password_confirmation %>

     	<%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>